### ISSUE TITLE
Renv Initialization

### ISSUE THREAD

**Issue by tcopple** [virtualstaticvoid/heroku-docker-r#13]
Familiar with Docker and R but not necessarily `Renv` when I build off your shiny container I receive this error from a Heroku push. Things seem to work fine locally.

```
remote: Removing intermediate container a0ecdf28fb36
remote:  ---> Running in 9f22d7eaff04
remote: Removing intermediate container 9f22d7eaff04
remote:  ---> Running in 61e67c590a3f
remote: Error in loadNamespace(name) : there is no package called ‘renv’
remote: Calls: :: ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
remote: Execution halted
remote: The command '/bin/sh -c if [ -f "/app/renv/activate.R" ]; then /usr/bin/R --no-save --quiet --slave -e 'renv::restore()'; fi;' returned a non-zero code: 1
remote:
```

It appears to me that the base image doesn't have Renv installed when it calls `restore`.  I can work around this but I wondered if I'm doing something wrong.

**Comment by virtualstaticvoid** [comment]
Hi @tcopple 

What is the contents of your `.Rprofile` file (if any) in the root of your project directory?

Usually it contains the line (following) to bootstrap `renv`.

```
source("renv/activate.R")
```

I suspect you have the script `./renv/activate.R` in your project, since `if [ -f "/app/renv/activate.R" ]; then` tests for the existence of this file, however `renv` isn't being "activated" via the `.Rprofile` file.

**Comment by tcopple** [comment]
This was the problem! Thanks for the suggestion. Being unfamiliar with the R app world in general I immediately added that specific dot file to my `.gitignore`.

**Comment by virtualstaticvoid** [comment]
Issue solved.
